### ISSUE TITLE
Adapting for integrate and fire neurons

### ISSUE THREAD

**Issue by LokeshMukraj** [arashsm79/path-integration-bump-attractor#1]
Hi there, I'm currently working on developing computational neuroscience simulations in Rust and found your very well written repository, I was wondering if it would be possible to adapt your methods to be used with simple integrate and fire neurons or Izhikevich neurons where the input is a simple weighted sum of inputs from each presynaptic neuron? Any ideas would be appreciated

**Comment by arashsm79** [comment]
Hey!
I guess [CoreNeuron](https://github.com/neuronsimulator/nrn/tree/master/src/coreneuron) would be a good place to start, if you want to go down the route of high performance simulation with Rust. The [Blue Brain Project](https://github.com/BlueBrain) also has a lot of repositories and documentation that might be useful.
